### ISSUE TITLE
[Botão de configurações]

### ISSUE THREAD

**Issue by marcelmendonca** [topicos20152/Android#4]
Pessoal, como vcs estão usando material design, aquela opção das settings, e a caixinha de mensagens da google ficam habilitadas e visíveis por padrão.

Como não há funções associadas ainda, recomendo que escondam.

Quanto ao resto do sistema, a parte funcional tá ok, e creio que é isso que importa por agora. Quanto ao design acho que seria interessante melhorar a visualização das datas, ao invés das listas.

**Comment by lilianrg** [comment]
Vou trabalhar nessa issue
