### ISSUE TITLE
Build a request to get every tasks from API

### ISSUE THREAD

**Issue by Maychell** [topicos20152/Android#6]
The idea is to refactor the method in DAO to get every tasks from API through the architecture from #5 th issue.

**Comment by victorvilar** [comment]
I'll be working on this.

**Comment by Maychell** [comment]
@victorvilar, I suppose you to use something like this:

> new ApiRequest("tasks", "GET", Class1.keys).execute();
> Where tasks is the method target on api; GET is the request method and Class1 is the class you're working on, and keys is an static method.

The return type is a list of Map<String, String>.

**Comment by jefferssongalvao** [comment]
I'll resolve this issue. Vilar will resolve issue #7
